version: "3.8"

networks:
    kafka_f05:
        external: true

services:
    zookeeper:
        image: bitnami/zookeeper:latest
        ports:
            - 21810:21810
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - kafka_f05

    kafka:
        image: bitnami/kafka:latest
        ports:
            - 9092:9092
            - 9093:9093
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://0.0.0.0:9092 #127.0.0.1:9092
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT
            - KAFKA_CFG_LISTENERS=CLIENT://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092
            - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
        depends_on:
            - zookeeper
        networks:
            - kafka_f05

    # producer:
    #     build:
    #         context: ./kafka_app/producer
    #         dockerfile: Dockerfile
    #     command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    #     ports:
    #         - 8080:8000
    #     volumes:
    #         - ./kafka_app/producer:/usr/src/app
    #     environment:
    #         - KAFKA_HOST=kafka
    #         - KAFKA_PORT=9092
    #         - KAFKA_TOPICS=jobs
    #     depends_on:
    #         - kafka
    #         - zookeeper

    # consumer:
    #     deploy:
    #         resources:
    #             reservations:
    #                 devices:
    #                     - driver: nvidia
    #                       count: 1
    #                       capabilities: [gpu]
    #     build:
    #         context: ./kafka_app/consumer
    #         dockerfile: Dockerfile
    #     command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    #     volumes:
    #         - ./kafka_app/consumer:/usr/src/app
    #         - /dados01/workspace/ufmg_2021_f05/datasets/obras-escolas/modelos_pretreinados/:/usr/src/app/app/obras/networks
    #     environment:
    #         - KAFKA_HOST=kafka
    #         - KAFKA_PORT=9092
    #         - KAFKA_TOPICS=jobs
    #     depends_on:
    #         - kafka
    #         - zookeeper
